#!/bin/bash

usage () {
  echo 'usage: misajour [-h] branch'
  echo 'Run misajour from a git repo to automatically update'
  echo 'and rebase a source branch onto the current branch'
}

if [ "$1" == -h ] ; then
  usage
  exit 0
fi

if [ "$1" ] ; then
  source=$1
else
  echo 'Must provide a source branch'
  exit 1
fi

(git rev-parse --git-dir >/dev/null 2>&1)

if [ $? -ne 0 ] ; then
  echo 'Not a git repository'
  usage
  exit 1
fi

git rev-parse --verify $source >/dev/null 2>&1

if [ $? -ne 0 ] ; then
  echo "Could not find branch $source"
  exit 1
fi

function current_branch()
{
  echo $(git rev-parse --abbrev-ref HEAD)
}

target=$(current_branch)

if [ "$target" == "$source" ]
then
  echo "Cannot `basename $0` the same branch"
  echo "Please use a different source"
  exit 1
fi

changes=$(git status --porcelain | wc -l)

if [ $changes -gt 0 ]
then
  echo "Cannot misajour: You have unstaged changes"
  echo "Please commit or stash them"
  exit 1
fi

echo "Preparing to rebase $source onto $target"
git checkout $source

echo "Updating $source..."
git pull -q --rebase
git checkout $target

if [ $target == $(current_branch) ]
then
  echo "Rebasing $source onto $target..."
  git rebase $source
else
  echo "Aborting: unable to switch back to $target"
  echo "There was a problem updating $source"
fi

exit $?

